node1:
	ssh -i "node1.pem" ec2-user@ec2-3-133-59-162.us-east-2.compute.amazonaws.com;

node2:
	ssh -i "node1.pem" ec2-user@ec2-18-217-40-167.us-east-2.compute.amazonaws.com;

node3:
	ssh -i "node1.pem" ec2-user@ec2-3-19-223-112.us-east-2.compute.amazonaws.com;