node1:
	chmod +x ./connect_aws_node_1.sh;
	./connect_aws_node_1.sh;

node2:
	chmod +x ./connect_aws_node_2.sh;
	./connect_aws_node_2.sh;

node3:
	chmod +x ./connect_aws_node_3.sh;
	./connect_aws_node_3.sh;