version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dockerdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=V3rYStR0nGP@ssW0rD
      - MYSQL_ROOT_PASSWORD=aDm1nStR0nGP@ssW0rD
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
    name: mysqldata
    external: false
