version: "3.8"

services:
  mysql:
    image: mysqlapinetwork
    build:
      context: .
      dockerfile: mysql/Dockerfile
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: flaskcompose
    build:
      context: .
      dockerfile: flask/Dockerfile
    depends_on:
      - mysql
    restart: always
    ports:
      - "5000:5000"
    networks:
      - dockercompose
    volumes:
      - /home/motta/source/docker-for-devs/section-7/6_bind_mount/flask:/app

networks:
  dockercompose:
