version: "3.8"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - backend

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env
    networks:
      - backend

volumes:
  mysqldata: {}

networks:
  backend:
    driver: bridge
