version: "3.8"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=motta
      - MYSQL_PASSWORD=secret

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    ports:
      - "8000:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=motta
      - WORDPRESS_DB_PASSWORD=secret
      - WORDPRESS_DB_NAME=wordpress

volumes:
  mysqldata: {}
